
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts  to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version #print the version for logging
  - docker build -t simple-node --build-arg NAME=${NAME} .
  - docker tag simple-node mkortmann/simple-node:latest

after_success:
# To run the docker login command non-interactively, you can set the --password-stdin flag
# provide a password through STDIN. It prevents the password from ending up in the shell's
# history, or log-files.
# so, the command below print the password to the password-stdin. It executed firstly the
# right side of the pipe, and then print the password
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mkortmann/simple-node
